name: Build KernelSU-Next with SUSFS and AnyKernel3 (LTS)

on:
  push:
    branches: [ main ]
  schedule:
    # Run daily at 02:00 UTC to catch updates
    - cron: '0 2 * * *'
  workflow_dispatch:

env:
  DEBIAN_FRONTEND: noninteractive
  KERNEL_TYPE: lts

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git curl rsync build-essential bc bison flex libssl-dev libelf-dev lz4
        
        # Install repo
        mkdir -p ~/.bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
        chmod a+x ~/.bin/repo
        echo "$HOME/.bin" >> $GITHUB_PATH

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git config --global init.defaultBranch main

    - name: Create workspace and get build info
      run: |
        mkdir -p workarea
        cd workarea
        
        # Generate build timestamp
        BUILD_DATE=$(date +"%Y%m%d")
        BUILD_TIME=$(date +"%H%M")
        BUILD_DATE_FORMATTED=$(date +"%Y-%m-%d")
        BUILD_TIME_FORMATTED=$(date +"%H:%M")
        KERNEL_NAME="kyernel-lts-${BUILD_DATE}-${BUILD_TIME}"
        
        echo "BUILD_DATE=${BUILD_DATE}" >> $GITHUB_ENV
        echo "BUILD_TIME=${BUILD_TIME}" >> $GITHUB_ENV
        echo "BUILD_DATE_FORMATTED=${BUILD_DATE_FORMATTED}" >> $GITHUB_ENV
        echo "BUILD_TIME_FORMATTED=${BUILD_TIME_FORMATTED}" >> $GITHUB_ENV
        echo "KERNEL_NAME=${KERNEL_NAME}" >> $GITHUB_ENV
        
        echo "Building: $KERNEL_NAME"

    - name: Clone repositories (force sync)
      run: |
        cd workarea
        
        # Force clone SUSFS repository for LTS
        echo "Force cloning SUSFS repository for LTS..."
        rm -rf susfs4ksu
        git clone https://gitlab.com/pershoot/susfs4ksu.git -b gki-android14-6.1-lts-dev
        
        # Force clone AnyKernel3
        echo "Force cloning AnyKernel3..."
        rm -rf AnyKernel3
        git clone https://github.com/enskye/AnyKernel3.git

    - name: Setup LTS kernel sources (force sync)
      run: |
        cd workarea
        
        # Clean and setup LTS kernel
        rm -rf gki-lts-kernel gki-kernel
        mkdir -p gki-lts-kernel gki-kernel
        
        # Setup GKI Monthly for components
        cd gki-kernel
        echo "Setting up GKI Monthly sources for components..."
        LATEST_TAG=$(git ls-remote --tags https://android.googlesource.com/kernel/manifest | grep "refs/tags/android14-6.1-" | grep -v "lts" | grep -v "\^{}" | sort -V | tail -1 | cut -d'/' -f3)
        
        if [[ -n "$LATEST_TAG" ]]; then
          echo "Using latest stable tag: $LATEST_TAG"
          repo init -u https://android.googlesource.com/kernel/manifest -b $LATEST_TAG --depth=1
        else
          echo "No stable tag found, using common-android14-6.1 branch"
          repo init -u https://android.googlesource.com/kernel/manifest -b common-android14-6.1 --depth=1
        fi
        
        echo "Starting repo sync..."
        repo sync -c --no-tags --force-sync -j$(nproc)
        
        # Setup LTS kernel
        cd ../gki-lts-kernel
        git clone https://android.googlesource.com/kernel/common.git -b android14-6.1-lts
        
        # Copy necessary components from GKI Monthly
        cd ..
        for i in build tools prebuilts external .repo; do 
          rsync -a gki-kernel/$i/ gki-lts-kernel/$i/ 2>/dev/null || true
        done
        
        cd gki-lts-kernel
        ln -sf build/kernel/kleaf/bazel.WORKSPACE WORKSPACE
        
        echo "✅ LTS kernel sources ready"

    - name: Create working directory
      run: |
        cd workarea
        
        # Create working directory for LTS build
        rm -rf gki-14-lts
        rsync -a gki-lts-kernel/ gki-14-lts/
        
        echo "WORK_DIR=gki-14-lts" >> $GITHUB_ENV
        echo "Working in: gki-14-lts"

    - name: Copy SUSFS module and patches
      run: |
        cd workarea/gki-14-lts
        
        echo "Copying SUSFS files..."
        cp -p ../susfs4ksu/kernel_patches/fs/* common/fs/
        cp -p ../susfs4ksu/kernel_patches/include/linux/* common/include/linux/
        
        # Use LTS-specific patch if available, otherwise fallback
        cp -p ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-android14-6.1-lts.patch common/ 2>/dev/null || \
        cp -p ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-android14-6.1.patch common/
        
        cp -p ../susfs4ksu/kernel_patches/60_scope-minimized_manual_hooks.patch common/

    - name: Apply SUSFS patches
      run: |
        cd workarea/gki-14-lts/common
        
        echo "Applying SUSFS patches..."
        # Apply LTS patch if it exists, otherwise use regular patch
        if [[ -f "50_add_susfs_in_gki-android14-6.1-lts.patch" ]]; then
          patch -p1 -ui 50_add_susfs_in_gki-android14-6.1-lts.patch
        else
          patch -p1 -ui 50_add_susfs_in_gki-android14-6.1.patch
        fi
        
        patch -p1 -ui 60_scope-minimized_manual_hooks.patch

    - name: Setup KernelSU-Next
      run: |
        cd workarea/gki-14-lts
        
        echo "Setting up KernelSU-Next..."
        curl -LSs "https://raw.githubusercontent.com/pershoot/KernelSU-Next/refs/heads/next-susfs/kernel/setup.sh" | bash -s next-susfs

    - name: Remove protected exports and set version
      run: |
        cd workarea/gki-14-lts
        
        echo "Removing protected exports for Wi-Fi/Bluetooth compatibility..."
        sed -i '/^[[:space:]]*"protected_exports_list"[[:space:]]*:[[:space:]]*"android\/abi_gki_protected_exports_aarch64",$/d' common/BUILD.bazel
        rm -f common/android/abi_gki_protected_exports_*
        
        # Clean up patch files
        rm -f common/50_add_susfs_in_gki-android14-6.1*.patch common/60_scope-minimized_manual_hooks.patch
        
        # Set custom kernel version
        echo 'echo "-kyernel"' > common/scripts/setlocalversion

    - name: Commit changes
      run: |
        cd workarea/gki-14-lts/common
        
        git add -A
        git commit -m "Add KernelSU-Next with SUSFS integration - $KERNEL_NAME"

    - name: Build kernel
      run: |
        cd workarea/gki-14-lts
        
        echo "Building kernel with fast configuration..."
        tools/bazel run --config=fast --config=stamp --lto=thin //common:kernel_aarch64_dist -- --dist_dir=../android-kernel

    - name: Prepare and sign kernel image
      run: |
        cd workarea/android-kernel
        
        echo "Built artifacts:"
        ls -la
        
        # Find and prepare kernel image
        if [[ -f "Image" ]]; then
          echo "Compressing Image to Image.lz4..."
          lz4 -9 -f Image Image.lz4
          KERNEL_IMAGE="Image.lz4"
        elif [[ -f "Image.gz" ]]; then
          echo "Converting Image.gz to Image.lz4..."
          gunzip Image.gz
          lz4 -9 -f Image Image.lz4
          KERNEL_IMAGE="Image.lz4"
        else
          echo "❌ No kernel image found!"
          exit 1
        fi
        
        echo "KERNEL_IMAGE=${KERNEL_IMAGE}" >> $GITHUB_ENV
        echo "✅ Kernel image prepared: $KERNEL_IMAGE"
        
        # Sign the kernel image if signing tools are available
        if command -v avbtool >/dev/null 2>&1; then
          echo "Signing kernel image..."
          avbtool add_hashtree_footer --image $KERNEL_IMAGE --partition_size 67108864 --partition_name boot
          echo "✅ Kernel image signed"
        else
          echo "⚠️ Signing tools not available, skipping signature"
        fi

    - name: Create AnyKernel3 package
      run: |
        cd workarea
        
        echo "Preparing AnyKernel3 package..."
        cd AnyKernel3
        
        # Copy kernel image
        cp ../android-kernel/$KERNEL_IMAGE .
        
        # Create ZIP package
        ZIP_NAME="${KERNEL_NAME}.zip"
        zip -r9 "../$ZIP_NAME" . -x "*.git*" "README.md" "LICENSE"
        
        cd ..
        echo "✅ Created: $ZIP_NAME"
        echo "Package size: $(du -h $ZIP_NAME | cut -f1)"

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.KERNEL_NAME }}
        name: ${{ env.KERNEL_NAME }}
        body: |
          ## 🚀 LTS Kernel Build - ${{ env.KERNEL_NAME }}
          
          **Build Information:**
          - **Kernel Type**: LTS (Long Term Support)
          - **Build Date**: ${{ env.BUILD_DATE_FORMATTED }}
          - **Build Time**: ${{ env.BUILD_TIME_FORMATTED }} UTC
          - **Auto-built**: Daily sync and build
          
          **Components:**
          - ✅ **KernelSU-Next**: Latest with SUSFS integration
          - ✅ **SUSFS**: Advanced root hiding capabilities  
          - ✅ **AnyKernel3**: Universal flashing support
          - ✅ **Signed**: Image signed by default
          
          **Installation:**
          1. Download the ZIP file below
          2. Boot into custom recovery (TWRP/OrangeFox)
          3. Flash the ZIP file
          4. Reboot and enjoy!
          
          **Note**: This is an LTS build with enhanced stability and security features.
        files: |
          workarea/${{ env.KERNEL_NAME }}.zip
        draft: false
        prerelease: false

    - name: Upload raw kernel artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.KERNEL_NAME }}-raw-files
        path: workarea/android-kernel/
        retention-days: 7

    - name: Generate build summary
      run: |
        cd workarea
        
        echo "## 🚀 LTS Kernel Build Complete" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 📦 Package Information" >> $GITHUB_STEP_SUMMARY
        echo "- **Name**: \`$KERNEL_NAME\`" >> $GITHUB_STEP_SUMMARY
        echo "- **Type**: LTS (Long Term Support)" >> $GITHUB_STEP_SUMMARY
        echo "- **Build Date**: $BUILD_DATE_FORMATTED" >> $GITHUB_STEP_SUMMARY
        echo "- **Build Time**: $BUILD_TIME_FORMATTED UTC" >> $GITHUB_STEP_SUMMARY
        echo "- **Package**: \`$KERNEL_NAME.zip\`" >> $GITHUB_STEP_SUMMARY
        echo "- **Size**: $(du -h $KERNEL_NAME.zip | cut -f1)" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 🔧 Build Components" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ **KernelSU-Next**: Latest with SUSFS integration" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ **SUSFS**: Advanced root hiding capabilities" >> $GITHUB_SUMMARY
        echo "- ✅ **AnyKernel3**: Universal flashing support" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ **Kernel Image**: \`$KERNEL_IMAGE\` (Signed)" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ **Force Sync**: All sources updated" >> $GITHUB_STEP_SUMMARY
