# .github/workflows/build-kernel.yml

name: Build GKI Kernel with KernelSU & susfs4ksu

on:
  workflow_dispatch: # Allows you to run this workflow manually

jobs:
  build:
    name: Build GKI Kernel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Workflow Repo
        uses: actions/checkout@v4

      - name: Install Dependencies & Setup Repo Tool
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses-dev lib32readline
          
