name: Android Kernel Build (Official Method)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git wget curl build-essential bc flex bison libssl-dev libelf-dev python3 zip repo
        
    - name: Setup repo and sync sources
      run: |
        mkdir android-kernel && cd android-kernel
        repo init -u https://android.googlesource.com/kernel/manifest -b common-android14-6.1-lts
        repo sync
        
    - name: Setup KernelSU
      run: |
        cd android-kernel/common
        curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main
        
    - name: Setup SUSFS4KSU
      run: |
        cd android-kernel/common
        mkdir -p KernelSU/userspace
        git clone -b gki-android14-6.1 --depth=1 https://gitlab.com/simonpunk/susfs4ksu.git KernelSU/userspace/susfs4ksu
        
    - name: Apply patches
      run: |
        cd android-kernel/common
        
        # KernelSU integration
        echo 'source "KernelSU/Kconfig"' >> drivers/Kconfig
        echo 'obj-$(CONFIG_KSU) += KernelSU/' >> drivers/Makefile
        
        # Try SUSFS patch
        if [ -f "KernelSU/userspace/susfs4ksu/kernel_patches/susfs_for_ksu.patch" ]; then
          patch -p1 < KernelSU/userspace/susfs4ksu/kernel_patches/susfs_for_ksu.patch || echo "Patch failed, continuing..."
        fi
        
    - name: Configure kernel for KernelSU and SUSFS4KSU
      run: |
        cd android-kernel
        
        # Create config fragment with all SUSFS4KSU options
        cat > gki_ksu_susfs.fragment << 'EOF'
        # KernelSU
        CONFIG_KSU=y
        CONFIG_KSU_DEBUG=y
        
        # SUSFS4KSU
        CONFIG_SUSFS=y
        CONFIG_SUSFS_SUS_SU=y
        CONFIG_SUSFS_SUS_MOUNT=y  
        CONFIG_SUSFS_SUS_KSTAT=y
        CONFIG_SUSFS_SUS_OVERLAYFS=y
        CONFIG_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y
        CONFIG_SUSFS_SUS_PATH=y
        CONFIG_SUSFS_TRY_UMOUNT=y
        EOF
        
        # Add fragment to build config
        echo "FRAGMENT_CONFIG=gki_ksu_susfs.fragment" >> build.config.gki.aarch64
        
    - name: Build kernel
      run: |
        cd android-kernel
        BUILD_CONFIG=build.config.gki.aarch64 build/build.sh
        
    - name: Prepare artifacts
      run: |
        cd android-kernel
        mkdir -p artifacts
        
        # Copy kernel images
        find out -name "Image" -exec cp {} artifacts/ \;
        find out -name "Image.gz" -exec cp {} artifacts/ \;  
        find out -name "Image.lz4" -exec cp {} artifacts/ \;
        find out -name "*.img" -exec cp {} artifacts/ \;
        
        # Copy to dist directory if needed
        cp -r out/*/dist/* artifacts/ 2>/dev/null || true
        
        # Build info
        echo "Build: $(date)" > artifacts/build-info.txt
        echo "Branch: common-android14-6.1-lts" >> artifacts/build-info.txt
        echo "KernelSU: YES" >> artifacts/build-info.txt
        echo "SUSFS4KSU: YES (gki-android14-6.1)" >> artifacts/build-info.txt
        
        ls -la artifacts/
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: android-kernel-ksu-susfs
        path: android-kernel/artifacts/
        retention-days: 30
