# .github/workflows/build-kernel.yml

name: Build GKI Kernel with KernelSU & susfs4ksu

on:
  workflow_dispatch: # Allows you to run this workflow manually

jobs:
  build:
    name: Build GKI Kernel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Workflow Repo
        uses: actions/checkout@v4

      - name: Install Dependencies & Setup Repo Tool
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses-dev lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libncurses-dev libsdl2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
          mkdir -p ~/.bin
          curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
          chmod a+x ~/.bin/repo
          echo "$HOME/.bin" >> $GITHUB_PATH
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Initialize & Sync GKI Kernel Source
        run: |
          mkdir kernel && cd kernel
          repo init -u https://android.googlesource.com/kernel/manifest -b common-android14-6.1-2025-08 --depth=1
          repo sync -c --no-tags --no-clone-bundle -j$(nproc --all)
          echo "KERNEL_REPO=$GITHUB_WORKSPACE/kernel" >> $GITHUB_ENV

      - name: Integrate KernelSU
        working-directory: ${{ env.KERNEL_REPO }}
        run: |
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main
          echo "✅ KernelSU integrated successfully."

      - name: Integrate susfs4ksu (Ignoring Failures)
        run: |
          echo "Cloning susfs4ksu repository..."
          git clone https://gitlab.com/simonpunk/susfs4ksu.git --depth=1 --branch gki-android14-6.1 /tmp/susfs4ksu

          echo "Copying susfs source and patch files..."
          cp /tmp/susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch ${{ env.KERNEL_REPO }}/KernelSU/
          cp /tmp/susfs4ksu/kernel_patches/50_add_susfs_in_gki-android14-6.1.patch ${{ env.KERNEL_REPO }}/common/
          cp -r /tmp/susfs4ksu/kernel_patches/fs/* ${{ env.KERNEL_REPO }}/common/fs/
          cp -r /tmp/susfs4ksu/kernel_patches/include/linux/* ${{ env.KERNEL_REPO }}/common/include/linux/

          echo "Applying patches and ignoring failures..."
          # Apply the KernelSU-specific patch, ignoring rejects
          cd ${{ env.KERNEL_REPO }}/KernelSU && patch -p1 --fuzz=3 < 10_enable_susfs_for_ksu.patch || true

          # Apply the main kernel patch, ignoring rejects
          cd ${{ env.KERNEL_REPO }}/common && patch -p1 --fuzz=3 < 50_add_susfs_in_gki-android14-6.1.patch || true
          echo "✅ susfs4ksu integration attempted."

      - name: Configure Kernel Parameters
        run: |
          BUILD_CONFIG_PATH="${{ env.KERNEL_REPO }}/common/build.config.gki.aarch64"
          echo "Appending required kernel parameters..."
          echo "CONFIG_KSU_SUSFS=y" >> $BUILD_CONFIG_PATH
          echo "✅ Kernel parameters configured."

      - name: Apply GKI Android 14+ Fixes
        run: |
          rm -f $KERNEL_REPO/common/android/abi_gki_protected_exports_aarch64
          rm -f $KERNEL_REPO/common/android/abi_gki_protected_exports_x86_64
          echo "✅ GKI ABI files removed."

      - name: Build Kernel with Bazel (Kleaf)
        id: build
        working-directory: ${{ env.KERNEL_REPO }}
        run: |
          LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh
          echo "✅ Kernel build completed."
          echo "Contents of dist directory:"
          ls -R $DIST_DIR

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-artifacts
          path: ${{ env.KERNEL_REPO }}/out/dist/
          if-no-files-found: error
