name: Build KernelSU-Next with SUSFS

on:
  workflow_dispatch:
    inputs:
      kernel_type:
        description: 'Kernel type to build'
        required: true
        default: 'gki'
        type: choice
        options:
        - gki
        - lts
      manifest_number:
        description: 'Manifest number (optional - will use latest android14-6.1 if not available)'
        required: false
        type: string
      build_config:
        description: 'Build configuration'
        required: false
        default: 'fast'
        type: choice
        options:
        - fast
        - release
        - debug

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git curl rsync build-essential bc bison flex libssl-dev libelf-dev
        
        # Install repo
        mkdir -p ~/.bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
        chmod a+x ~/.bin/repo
        echo "$HOME/.bin" >> $GITHUB_PATH

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git config --global init.defaultBranch main

    - name: Create workspace
      run: |
        mkdir -p workarea
        cd workarea

    - name: Clone SUSFS repository
      run: |
        cd workarea
        if [[ "${{ inputs.kernel_type }}" == "lts" ]]; then
          git clone --depth 2 --no-tags https://gitlab.com/pershoot/susfs4ksu.git -b gki-android14-6.1-lts-dev
        else
          git clone --depth 2 --no-tags https://gitlab.com/pershoot/susfs4ksu.git -b gki-android14-6.1-dev
        fi

    - name: Setup kernel sources
      run: |
        cd workarea
        mkdir -p gki-kernel android-kernel
        cd gki-kernel
        
        echo "Initializing kernel manifest repository..."
        
        # If a specific manifest number is provided, try to use it
        if [[ -n "${{ inputs.manifest_number }}" ]]; then
          echo "Checking for build-${{ inputs.manifest_number }} tag..."
          if git ls-remote --tags https://android.googlesource.com/kernel/manifest | grep -q "refs/tags/build-${{ inputs.manifest_number }}$"; then
            echo "Found specific build tag, using build-${{ inputs.manifest_number }}"
            repo init -u https://android.googlesource.com/kernel/manifest -b refs/tags/build-${{ inputs.manifest_number }} --depth=2
          else
            echo "Build tag not found, using latest android14-6.1 branch"
            repo init -u https://android.googlesource.com/kernel/manifest -b common-android14-6.1 --depth=2
          fi
        else
          echo "No manifest number provided, using latest android14-6.1 branch"
          repo init -u https://android.googlesource.com/kernel/manifest -b common-android14-6.1 --depth=2
        fi
        
        echo "Starting repo sync..."
        repo sync -c --no-tags -j$(nproc)
        echo "Repo sync completed"
        
        # Verify we have the kernel sources
        echo "Checking kernel sources:"
        ls -la
        if [[ -d "common" ]]; then
          echo "✅ Common kernel directory found"
          cd common
          echo "Kernel version info:"
          make kernelversion 2>/dev/null || echo "Could not determine kernel version"
          cd ..
        else
          echo "❌ Common kernel directory not found"
        fi

    - name: Setup LTS kernel (if LTS build)
      if: inputs.kernel_type == 'lts'
      run: |
        cd workarea/gki-kernel
        # For LTS, clone the LTS branch directly into common directory
        rm -rf common
        git clone --depth 2 --no-tags https://android.googlesource.com/kernel/common.git -b android14-6.1-lts common
        ln -sf build/kernel/kleaf/bazel.WORKSPACE WORKSPACE

    - name: Copy SUSFS module and patches
      run: |
        cd workarea/gki-kernel
        
        # Copy SUSFS files
        cp -p ../susfs4ksu/kernel_patches/fs/* common/fs/
        cp -p ../susfs4ksu/kernel_patches/include/linux/* common/include/linux/
        
        if [[ "${{ inputs.kernel_type }}" == "lts" ]]; then
          cp -p ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-android14-6.1-lts.patch common/ 2>/dev/null || \
          cp -p ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-android14-6.1.patch common/
        else
          cp -p ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-android14-6.1.patch common/
        fi
        
        cp -p ../susfs4ksu/kernel_patches/60_scope-minimized_manual_hooks.patch common/

    - name: Apply patches
      run: |
        cd workarea/gki-kernel/common
        
        # Apply SUSFS patches
        if [[ -f "50_add_susfs_in_gki-android14-6.1-lts.patch" ]]; then
          patch -p1 -ui 50_add_susfs_in_gki-android14-6.1-lts.patch
        else
          patch -p1 -ui 50_add_susfs_in_gki-android14-6.1.patch
        fi
        
        patch -p1 -ui 60_scope-minimized_manual_hooks.patch

    - name: Setup KernelSU-Next
      run: |
        cd workarea/gki-kernel
        
        # Pull down KernelSU-Next and execute setup
        curl -LSs "https://raw.githubusercontent.com/pershoot/KernelSU-Next/refs/heads/next-susfs/kernel/setup.sh" | bash -s next-susfs

    - name: Remove protected exports
      run: |
        cd workarea/gki-kernel
        
        # Remove protected exports for Wi-Fi and Bluetooth functionality
        sed -i '/^[[:space:]]*"protected_exports_list"[[:space:]]*:[[:space:]]*"android\/abi_gki_protected_exports_aarch64",$/d' common/BUILD.bazel
        rm -f common/android/abi_gki_protected_exports_* common/50_add_susfs_in_gki-android14-6.1*.patch common/60_scope-minimized_manual_hooks.patch

    - name: Commit changes
      run: |
        cd workarea/gki-kernel/common
        
        git add -A
        git commit -a -m "Add KernelSU-Next-susfs with SUSFS integration"

    - name: Build kernel
      run: |
        cd workarea/gki-kernel
        
        # Build the kernel
        tools/bazel run --config=${{ inputs.build_config }} --config=stamp --lto=thin //common:kernel_aarch64_dist -- --dist_dir=../android-kernel

    - name: Prepare boot image components
      run: |
        cd workarea/android-kernel
        mkdir -p kernel
        
        # List built artifacts
        echo "Built kernel artifacts:"
        ls -la
        
        # Copy kernel image if it exists
        if [[ -f "Image" ]]; then
          cp Image kernel/
        elif [[ -f "Image.gz" ]]; then
          cp Image.gz kernel/
        fi

    - name: Upload kernel artifacts
      uses: actions/upload-artifact@v4
      with:
        name: kernelsu-susfs-${{ inputs.kernel_type }}-kernel-${{ inputs.manifest_number || 'latest' }}
        path: |
          workarea/android-kernel/
        retention-days: 30

    - name: Generate build summary
      run: |
        echo "## Build Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Kernel Type**: ${{ inputs.kernel_type }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Manifest**: ${{ inputs.manifest_number || 'Latest android14-6.1' }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Build Config**: ${{ inputs.build_config }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Build Status**: ✅ Success" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Artifacts Built:" >> $GITHUB_STEP_SUMMARY
        cd workarea/android-kernel
        for file in *; do
          if [[ -f "$file" ]]; then
            echo "- $file ($(stat -c%s "$file" | numfmt --to=iec-i))" >> $GITHUB_STEP_SUMMARY
          fi
        done
