# .github/workflows/build-kernel.yml

name: Build GKI Kernel with KernelSU & susfs4ksu

on:
  workflow_dispatch: # Allows you to run this workflow manually

jobs:
  build:
    name: Build GKI Kernel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Workflow Repo
        uses: actions/checkout@v4

      - name: Install Dependencies & Setup Repo Tool
        run: |
          sudo apt-get update
          sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses-dev lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libncurses-dev libsdl2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
          mkdir -p ~/.bin && curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo && chmod a+x ~/.bin/repo
          export PATH="$HOME/.bin:$PATH"
          git config --global user.name "GitHub Actions" && git config --global user.email "actions@github.com"

      - name: Initialize & Sync GKI Kernel Source
        run: |
          mkdir kernel && cd kernel
          repo init -u https://android.googlesource.com/kernel/manifest -b common-android14-6.1 --depth=1
          repo sync -c --no-tags --no-clone-bundle -j$(nproc --all)
          echo "KERNEL_REPO=$GITHUB_WORKSPACE/kernel" >> $GITHUB_ENV

      - name: Integrate KernelSU
        working-directory: ${{ env.KERNEL_REPO }}
        run: |
          # Use the official setup script
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main
          echo "✅ KernelSU integrated successfully."

      - name: Integrate susfs4ksu
        working-directory: ${{ env.KERNEL_REPO }}/common
        run: |
          # Clone the specified branch of the susfs4ksu repo
          git clone https://gitlab.com/simonpunk/susfs4ksu.git --depth=1 --branch gki-android14-6.1 /tmp/susfs4ksu
          
          # Apply the patch from the cloned repo
          git apply /tmp/susfs4ksu/patches/android14-6.1/*.patch
          echo "✅ susfs4ksu integrated successfully."

      - name: Apply GKI Android 14+ Fixes
        run: |
          # Remove ABI symbol list files that can cause module loading issues
          rm -f $KERNEL_REPO/common/android/abi_gki_protected_exports_aarch64
          rm -f $KERNEL_REPO/common/android/abi_gki_protected_exports_x86_64
          echo "✅ GKI ABI files removed."

      - name: Build Kernel with Bazel (Kleaf)
        id: build
        working-directory: ${{ env.KERNEL_REPO }}
        run: |
          # Start the build. The integration scripts handle the config.
          LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh
          echo "✅ Kernel build completed."
          echo "Contents of dist directory:"
          ls -R $DIST_DIR

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: kernel-artifacts
          path: ${{ env.KERNEL_REPO }}/out/dist/
          if-no-files-found: error
