name: Build GKI Kernel with KernelSU

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Install Dependencies & Setup Tools
      run: |
        # Add Bazel's apt repository
        sudo apt-get update
        sudo apt-get install -y apt-transport-https curl gnupg
        curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg
        sudo mv bazel.gpg /etc/apt/trusted.gpg.d/
        echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
        
        # Install all dependencies
        sudo apt-get update
        sudo apt-get install -y git curl rsync bazel
        
        # Setup 'repo' tool
        mkdir -p ~/.bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
        chmod a+x ~/.bin/repo
        echo "$HOME/.bin" >> $GITHUB_PATH

    - name: 2. Download Manifest File
      run: |
        # Please replace 'your_manifest_file.xml' with the actual filename from the enskye/kernel_patches repo.
        curl -o manifest_13722573.xml https://raw.githubusercontent.com/enskye/kernel_patches/main/manifest_13722573.xml

    - name: 3. Clone SuSFS Repository
      run: |
        git clone https://gitlab.com/pershoot/susfs4ksu.git -b gki-android14-6.1-dev

    - name: 4. Create Directories
      run: |
        mkdir gki-kernel android-kernel

    - name: 5. Pull Down GKI Repository
      working-directory: ./gki-kernel
      run: |
        repo init -u https://android.googlesource.com/kernel/manifest
        cp ../manifest_13722573.xml .repo/manifests/
        repo init -m manifest_13722573.xml
        repo --trace sync -j$(nproc --all)

    - name: 7. Copy SuSFS Patches
      working-directory: ./gki-kernel
      run: |
        cp -p ../susfs4ksu/kernel_patches/fs/* common/fs
        cp -p ../susfs4ksu/kernel_patches/include/linux/* common/include/linux
        cp -p ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-android14-6.1.patch common
        cp -p ../susfs4ksu/kernel_patches/60_scope-minimized_manual_hooks.patch common

    - name: 8. Apply Patches
      working-directory: ./gki-kernel/common
      run: |
        patch -p1 < 50_add_susfs_in_gki-android14-6.1.patch
        patch -p1 < 60_scope-minimized_manual_hooks.patch

    - name: 9. Integrate KernelSU-Next
      working-directory: ./gki-kernel
      run: |
        curl -LSs "https://raw.githubusercontent.com/pershoot/KernelSU-Next/refs/heads/next-susfs/kernel/setup.sh" | bash -s next-susfs

    - name: 10. Clean Up Patches and Exports
      working-directory: ./gki-kernel
      run: |
        sed -i '/^[[:space:]]*"protected_exports_list"[[:space:]]*:[[:space:]]*"android\/abi_gki_protected_exports_aarch64",$/d' common/BUILD.bazel
        rm common/android/abi_gki_protected_exports_* common/50_add_susfs_in_gki-android14-6.1.patch common/60_scope-minimized_manual_hooks.patch
        
    - name: 11. Deleted -dirty tag
      run: |
        cd gki-kernel
        sed -i "/stable_scmversion_cmd/s/-maybe-dirty//g" ./build/kernel/kleaf/impl/stamp.bzl || echo "No stamp.bzl!" 
        sed -i 's/-dirty//' ./common/scripts/setlocalversion 
        sed -i 's/-dirty//' ./msm-kernel/scripts/setlocalversion 
        sed -i 's/-dirty//' ./external/dtc/scripts/setlocalversion 
        sed -i 's/-dirty//' ./build/kernel/kleaf/workspace_status_stamp.py || echo "No workspace_status_stamp.py!"
        
    - name: 12. Build the Kernel
      run: |
        cd gki-kernel
        tools/bazel run --config=fast --config=stamp --lto=thin //common:kernel_aarch64_dist -- --dist_dir=../android-kernel

    - name: 13. Upload Kernel Artifact
      uses: actions/upload-artifact@v4
      with:
        name: kernel-image
        path: android-kernel/
