name: Build GKI 14-6.1 with KernelSU + susfs4ksu

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential bc bison flex \
            libssl-dev libncurses5-dev ccache curl wget unzip patch \
            python3 zip unzip rsync

      - name: Clone kernel source (force fresh)
        run: |
          rm -rf kernel_src
          git clone --depth=1 https://android.googlesource.com/kernel/common -b android14-6.1-lts kernel_src

      - name: Integrate KernelSU
        working-directory: kernel_src
        run: |
          curl -LSs https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh | bash -

      - name: Clone susfs4ksu
        run: |
          rm -rf susfs
          git clone --depth=1 -b gki-android14-6.1 https://gitlab.com/simonpunk/susfs4ksu.git susfs

      - name: Apply susfs4ksu patches
        working-directory: kernel_src
        run: |
          patch -p1 < ../susfs/patches/50_add_susfs_in_gki-android14-6.1.patch
          patch -p1 < ../susfs/patches/10_enable_susfs_for_ksu.patch

      - name: Enable configs
        working-directory: kernel_src
        run: |
          echo "CONFIG_KSU=y" >> common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS=y" >> common/arch/arm64/configs/gki_defconfig

      - name: Build with Bazel
        working-directory: kernel_src
        run: |
          LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gki-android14-6.1-ksu-susfs
          path: kernel_src/out/dist/*
