name: Build GKI Kernel

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Maximize Build Space
      uses: AdityaGarg8/remove-unwanted-software@v5
      with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          remove-codeql: 'true'
          remove-docker-images: 'true'
          remove-large-packages: 'true'
          remove-swapfile: 'true'
          remove-cached-tools: 'false'
          verbose: 'false'
          
    - name: Install Dependencies & Setup Tools
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https curl gnupg git rsync
        curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/bazel.gpg > /dev/null
        echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
        sudo apt-get update
        sudo apt-get install -y bazel
        mkdir -p ~/.bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
        chmod a+x ~/.bin/repo
        echo "$HOME/.bin" >> $GITHUB_PATH

    - name: Clone Source Repositories
      run: |
        git clone https://gitlab.com/pershoot/susfs4ksu.git -b gki-android14-6.1-dev
        git clone https://github.com/enskye/kernel_patches.git -b main

    - name: Initialize and Sync GKI Repository
      run: |
        mkdir gki-kernel
        cd gki-kernel
        repo init --depth=1 -u https://android.googlesource.com/kernel/manifest
        cp ../kernel_patches/manifest_13884750.xml .repo/manifests/
        repo init --depth=1 -m manifest_13884750.xml
        repo sync

    - name: Copy and Apply Patches
      working-directory: ./gki-kernel
      run: |
        cp -p ../susfs4ksu/kernel_patches/fs/* common/fs/
        cp -p ../susfs4ksu/kernel_patches/include/linux/* common/include/linux/
        cp -p ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-android14-6.1.patch common/
        cp -p ../susfs4ksu/kernel_patches/60_scope-minimized_manual_hooks.patch common/
        cd common
        patch -p1 < 50_add_susfs_in_gki-android14-6.1.patch
        patch -p1 < 60_scope-minimized_manual_hooks.patch

    - name: Integrate KernelSU-Next
      working-directory: ./gki-kernel
      run: curl -LSs "https://raw.githubusercontent.com/pershoot/KernelSU-Next/refs/heads/next-susfs/kernel/setup.sh" | bash -s next-susfs

    - name: Clean Up Patches and Build Files
      working-directory: ./gki-kernel
      run: |
        sed -i '/^[[:space:]]*"protected_exports_list"[[:space:]]*:[[:space:]]*"android\/abi_gki_protected_exports_aarch64",$/d' common/BUILD.bazel
        rm common/android/abi_gki_protected_exports_* common/50_add_susfs_in_gki-android14-6.1.patch common/60_scope-minimized_manual_hooks.patch

    - name: Set Custom Kernel Version
      working-directory: ./gki-kernel
      run: |
        echo 'echo "-android14-11-ga4b2a2c52a04-ab13615798"' > common/scripts/setlocalversion
        sed -i "/stable_scmversion_cmd/s/-maybe-dirty//g" build/kernel/kleaf/impl/stamp.bzl || echo "No stamp.bzl!"
        sed -i 's/-dirty//' common/scripts/setlocalversion
        sed -i 's/-dirty//' build/kernel/kleaf/workspace_status_stamp.py || echo "No workspace_status_stamp.py!"

    - name: Set Boot Sign Key
      id: sign_setup
      env:
        BOOT_SIGN_KEY_PEM: ${{ secrets.BOOT_SIGN_KEY_PEM }}
        BOOT_SIGN_KEY_X509: ${{ secrets.BOOT_SIGN_KEY_X509 }}
      run: |
        if [ -n "$BOOT_SIGN_KEY_PEM" ] && [ -n "$BOOT_SIGN_KEY_X509" ]; then
          echo "✅ Signing keys found, configuring for a signed build..."
          mkdir -p ./gki-kernel/build/kernel
          echo "$BOOT_SIGN_KEY_PEM" > ./gki-kernel/build/kernel/rsa.pem
          echo "$BOOT_SIGN_KEY_X509" > ./gki-kernel/build/kernel/x509.pem
          echo "SIGN_FLAG=--config=boot_sign" >> $GITHUB_ENV
        else
          echo "⚠️ Signing keys not found, proceeding with an unsigned build."
        fi

    - name: Define Boot Sign Config
      if: env.SIGN_FLAG
      working-directory: ./gki-kernel
      run: |
        echo "build:boot_sign --//common:sign_boot_image=true" > user.bazelrc
        echo "✅ Created user.bazelrc to define boot_sign config."

    - name: Build the Kernel
      working-directory: ./gki-kernel
      run: tools/bazel --bazelrc=user.bazelrc run --config=fast --config=stamp ${{ env.SIGN_FLAG }} --lto=thin //common:kernel_aarch64_dist -- --dist_dir=../android-kernel

    - name: Package Kernel into Flashable Zip
      run: |
        KERNEL_IMAGE="android-kernel/Image.lz4"
        if [ ! -f "$KERNEL_IMAGE" ]; then
          echo "::error::Kernel image not found at $KERNEL_IMAGE!"
          exit 1
        fi
        git clone https://github.com/enskye/AnyKernel3.git -b gki-2.0
        cp "$KERNEL_IMAGE" AnyKernel3/
        mkdir -p release
        cd AnyKernel3
        sed -i "s/kernel.string=.*/kernel.string=kyernel-gki-$(date +%Y%m%d) by enskye/" anykernel.sh
        zip -r9 "../release/kyernel-$(date +%Y%m%d).zip" * -x .git README.md *placeholder

    - name: Create Release and Upload Kernel
      uses: softprops/action-gh-release@v2
      with:
        files: release/*.zip
        name: "kyernel Build #${{ github.run_number }} (${{ env.BUILD_DATE }})"
        tag_name: "kyernel-${{ github.run_number }}"
        body: |
          Automated GKI kernel build with KernelSU.
          Flashable zip attached below.
        make_latest: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BUILD_DATE: $(date +'%Y-%m-%d')
        
