name: Build LTS Kernel with SUSFS & KernelSU

on:
  workflow_dispatch:

env:
  KERNEL_NAME: kyernel
  BUILD_DATE: ${{ github.run_started_at }}

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip bc bison build-essential ccache curl flex g++-multilib gcc-multilib \
            libncurses5-dev libssl-dev libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip \
            zlib1g-dev openjdk-11-jdk python3 python-is-python3

      - name: Setup workarea
        run: |
          mkdir -p workarea
          cd workarea
          git clone --depth=1 https://android.googlesource.com/kernel/common gki-14-lts
          git clone --depth=1 https://github.com/AnyKernel3/AnyKernel3

      - name: Inject KernelSU (official way)
        run: |
          cd workarea/gki-14-lts
          curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -

      - name: Enable KernelSU & susfs4ksu configs
        run: |
          cd workarea/gki-14-lts/common

          # KernelSU core
          echo "CONFIG_KSU=y" >> arch/arm64/configs/gki_defconfig

          # SUSFS for KernelSU (full set)
          echo "CONFIG_KSU_SUSFS=y" >> arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_MNT=y" >> arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_SU=y" >> arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_SU=y" >> arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_HIDE_SUS_SU=y" >> arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_SU_RANDOM_OFFSET=y" >> arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_PROC_FILTER=y" >> arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y" >> arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_UMOUNT_BRANCH_CMD=y" >> arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE=y" >> arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y" >> arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y" >> arch/arm64/configs/gki_defconfig

      - name: Build kernel
        run: |
          cd workarea/gki-14-lts
          tools/bazel build //common:kernel_aarch64_dist
          mkdir -p android-kernel
          cp -v bazel-bin/common/kernel_aarch64/Image android-kernel/

      - name: Create AnyKernel3 package
        run: |
          cd workarea/AnyKernel3
          cp ../android-kernel/Image zImage
          BUILD_TAG="${KERNEL_NAME}-$(date +'%Y-%m-%d')-r${GITHUB_RUN_NUMBER}"
          echo "BUILD_TAG=$BUILD_TAG" >> $GITHUB_ENV
          zip -r9 "../$BUILD_TAG.zip" . -x "*.git*" "README.md" "LICENSE"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.BUILD_TAG }}
          name: ${{ env.BUILD_TAG }}
          body: |
            ## 🚀 LTS Kernel Build - ${{ env.BUILD_TAG }}

            **Build Information:**
            - **Kernel Type**: LTS (Long Term Support)
            - **Build Date**: $(date +'%Y-%m-%d')
            - **Run Number**: ${{ github.run_number }}

            **Components:**
            - ✅ **KernelSU** (official injection via setup.sh)
            - ✅ **susfs4ksu** root hiding
            - ✅ **AnyKernel3** universal flashing
