name: Build KernelSU-Next with SuSFS GKI

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-kernelsu:
    runs-on: ubuntu-latest

    env:
      REPO_PATH: ${{ github.workspace }}/repo
      WORKAREA: ${{ github.workspace }}/workarea
      GKI_KERNEL: ${{ github.workspace }}/workarea/gki-kernel
      SUSFS_REPO: susfs4ksu
      SUSFS_BRANCH: gki-android14-6.1-dev
      KERNEL_REPO_MANIFEST: manifest_xxxxx.xml
      KERNEL_REPO_MANIFEST_URL: https://raw.githubusercontent.com/enskye/kernel_patches/main/manifest_xxxxx.xml

    steps:
    - name: Checkout this repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git curl repo rsync bazel build-essential

    - name: Setup repo tool
      run: |
        mkdir -p ~/.bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
        chmod a+x ~/.bin/repo
        echo "$HOME/.bin" >> $GITHUB_PATH

    - name: Create workarea
      run: |
        mkdir -p $WORKAREA
        cd $WORKAREA
        mkdir gki-kernel android-kernel

    - name: Download manifest file from enskye repo
      run: |
        curl -o $WORKAREA/$KERNEL_REPO_MANIFEST $KERNEL_REPO_MANIFEST_URL

    - name: Initialize kernel repo with manifest
      run: |
        cd $GKI_KERNEL
        repo init -u https://android.googlesource.com/kernel/manifest
        cp -p $WORKAREA/$KERNEL_REPO_MANIFEST .repo/manifests/
        repo init -m $KERNEL_REPO_MANIFEST
        repo sync

    - name: Clone susfs4ksu repo
      run: |
        git clone -b $SUSFS_BRANCH https://gitlab.com/pershoot/susfs4ksu.git $WORKAREA/$SUSFS_REPO

    - name: Create mirror and apply patches
      run: |
        cd $WORKAREA
        rsync -a --del gki-kernel/ gki-14
        cd gki-14
        cp -p ../susfs4ksu/kernel_patches/fs/* common/fs
        cp -p ../susfs4ksu/kernel_patches/include/linux/* common/include/linux
        cp -p ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-android14-6.1.patch common
        cp -p ../susfs4ksu/kernel_patches/60_scope-minimized_manual_hooks.patch common
        cd common
        patch -p1 < 50_add_susfs_in_gki-android14-6.1.patch
        patch -p1 < 60_scope-minimized_manual_hooks.patch
        cd ..
        sed -i '/^[[:space:]]*"protected_exports_list"[[:space:]]*:[[:space:]]*"android\/abi_gki_protected_exports_aarch64",$/d' common/BUILD.bazel
        rm common/android/abi_gki_protected_exports_* common/50_add_susfs_in_gki-android14-6.1.patch common/60_scope-minimized_manual_hooks.patch

    - name: Commit patch changes
      run: |
        cd $WORKAREA/gki-14/common
        git add -A
        git commit -m "Add KernelSU-Next-susfs" || echo "No changes to commit"

    - name: Build kernel with bazel
      run: |
        cd $WORKAREA/gki-14
        tools/bazel run --config=fast --config=stamp --lto=thin //common:kernel_aarch64_dist -- --dist_dir=../android-kernel

    - name: Output build result files
      run: |
        ls -l $WORKAREA/android-kernel
