name: Build GKI Kernel

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Maximize Build Space
      uses: AdityaGarg8/remove-unwanted-software@v5
      with:
          remove-dotnet: 'true'          # Frees ~2 GB
          remove-android: 'true'         # Frees ~9 GB
          remove-haskell: 'true'         # Frees ~5.2 GB
          remove-codeql: 'true'          # Frees ~5.4 GB
          remove-docker-images: 'true'   # Frees ~3.2 GB
          remove-large-packages: 'true'  # Frees ~3.1 GB
          remove-swapfile: 'true'        # Frees ~4 GB
          remove-cached-tools: 'false'   # Avoid unless confirmed safe
          verbose: 'true'                # Enable detailed logging
 
    - name: Install Dependencies & Setup Tools
      run: |
        # Add Bazel's apt repository
        sudo apt-get update
        sudo apt-get install -y apt-transport-https curl gnupg
        curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg
        sudo mv bazel.gpg /etc/apt/trusted.gpg.d/
        echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
        
        # Install all dependencies
        sudo apt-get update
        sudo apt-get install -y git curl rsync bazel
        
        # Setup 'repo' tool
        mkdir -p ~/.bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
        chmod a+x ~/.bin/repo
        echo "$HOME/.bin" >> $GITHUB_PATH

    - name: Download Manifest File
      run: |
        # Please replace 'your_manifest_file.xml' with the actual filename from the enskye/kernel_patches repo.
        #curl -o manifest_13884750.xml https://raw.githubusercontent.com/enskye/kernel_patches/main/manifest_13722573.xml

    - name: Clone SuSFS Repository
      run: |
        git clone https://gitlab.com/pershoot/susfs4ksu.git -b gki-android14-6.1-dev
        git clone https://github.com/enskye/kernel_patches.git -b main
    - name: Create Directories
      run: |
        mkdir gki-kernel android-kernel

    - name: Pull Down GKI Repository
      working-directory: ./gki-kernel
      run: |
        repo init -u https://android.googlesource.com/kernel/manifest
        cp ../kernel_patches/manifest_july.xml .repo/manifests/
        repo init -m manifest_july.xml
        repo --trace sync -j$(nproc --all)

    - name: Copy SuSFS Patches
      working-directory: ./gki-kernel
      run: |
        cp -p ../susfs4ksu/kernel_patches/fs/* common/fs
        cp -p ../susfs4ksu/kernel_patches/include/linux/* common/include/linux
        cp -p ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-android14-6.1.patch common
        cp -p ../susfs4ksu/kernel_patches/60_scope-minimized_manual_hooks.patch common

    - name: Apply Patches
      working-directory: ./gki-kernel/common
      run: |
        patch -p1 < 50_add_susfs_in_gki-android14-6.1.patch
        patch -p1 < 60_scope-minimized_manual_hooks.patch

    - name: Integrate KernelSU-Next
      working-directory: ./gki-kernel
      run: |
        curl -LSs "https://raw.githubusercontent.com/pershoot/KernelSU-Next/refs/heads/next-susfs/kernel/setup.sh" | bash -s next-susfs

    - name: Clean Up Patches and Exports
      working-directory: ./gki-kernel
      run: |
        sed -i '/^[[:space:]]*"protected_exports_list"[[:space:]]*:[[:space:]]*"android\/abi_gki_protected_exports_aarch64",$/d' common/BUILD.bazel
        rm common/android/abi_gki_protected_exports_* common/50_add_susfs_in_gki-android14-6.1.patch common/60_scope-minimized_manual_hooks.patch
        
    - name: Rename kernel
      run: |
        #cd gki-kernel
        #echo 'echo "-kyernel"' > ./common/scripts/setlocalversion
        #sed -i "/stable_scmversion_cmd/s/-maybe-dirty//g" ./build/kernel/kleaf/impl/stamp.bzl || echo "No stamp.bzl!" 
        #sed -i 's/-dirty//' ./common/scripts/setlocalversion 
        #sed -i 's/-dirty//' ./build/kernel/kleaf/workspace_status_stamp.py || echo "No workspace_status_stamp.py!"
        
    - name: Build the Kernel
      run: |
        cd gki-kernel
        tools/bazel run --config=fast --config=stamp --lto=thin //common:kernel_aarch64_dist -- --dist_dir=../android-kernel

    - name: Upload Kernel Artifact
      uses: actions/upload-artifact@v4
      with:
        name: kernel-image
        path: android-kernel/
