name: Build GKI 14-6.1 with KernelSU + susfs4ksu

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git build-essential bc bison flex \
            libssl-dev libncurses5-dev ccache curl wget unzip patch \
            python3 zip unzip rsync

      - name: Clone kernel and susfs4ksu
        run: |
          git clone --depth=1 -b android14-6.1-lts https://android.googlesource.com/kernel/common kernel_src
          git clone --depth=1 -b gki-android14-6.1 https://gitlab.com/simonpunk/susfs4ksu.git

      - name: Integrate KernelSU and apply patches
        run: |
          cd kernel_src

          # KernelSU official integration
          curl -LSs https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh | bash

          # Copy patch files into kernel_src
          cp ../susfs4ksu/50_add_susfs_in_gki-android14-6.1.patch .
          cp ../susfs4ksu/kernel_patches/10_enable_susfs_for_ksu.patch .

          # Apply patches
          patch -p1 < 50_add_susfs_in_gki-android14-6.1.patch
          patch -p1 < 10_enable_susfs_for_ksu.patch

          # Enable configs
          echo "CONFIG_KSU=y" >> common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_KSU_SUSFS=y" >> common/arch/arm64/configs/gki_defconfig

          # Build kernel with Bazel
          LTO=thin BUILD_CONFIG=common/build.config.gki.aarch64 build/build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: gki-android14-6.1-ksu-susfs
          path: kernel_src/out/dist/*
