name: Build KernelSU-Next with SUSFS and AnyKernel3

on:
  workflow_dispatch:
env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y git curl rsync build-essential bc bison flex libssl-dev libelf-dev lz4
        
        # Install repo
        mkdir -p ~/.bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
        chmod a+x ~/.bin/repo
        echo "$HOME/.bin" >> $GITHUB_PATH

    - name: Set up Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git config --global init.defaultBranch main

    - name: Create workspace and get build info
      run: |
        mkdir -p workarea
        cd workarea
        
        # Generate build timestamp
        BUILD_DATE=$(date +"%Y%m%d")
        BUILD_TIME=$(date +"%H%M")
        KERNEL_NAME="kyernel-${BUILD_DATE}-${BUILD_TIME}"
        
        echo "BUILD_DATE=${BUILD_DATE}" >> $GITHUB_ENV
        echo "BUILD_TIME=${BUILD_TIME}" >> $GITHUB_ENV
        echo "KERNEL_NAME=${KERNEL_NAME}" >> $GITHUB_ENV
        
        echo "Building: $KERNEL_NAME"

    - name: Clone repositories
      run: |
        cd workarea
        
        # Clone SUSFS repository
        echo "Cloning SUSFS repository..."
        git clone --depth 2 --no-tags https://gitlab.com/pershoot/susfs4ksu.git -b gki-android14-6.1-dev
        
        # Clone AnyKernel3
        echo "Cloning AnyKernel3..."
        git clone --depth 1 https://github.com/enskye/AnyKernel3.git

    - name: Setup kernel sources with latest stable tag
      run: |
        cd workarea
        mkdir -p gki-kernel android-kernel
        cd gki-kernel
        
        echo "Finding latest stable android14-6.1 tag..."
        LATEST_TAG=$(git ls-remote --tags https://android.googlesource.com/kernel/manifest | grep "refs/tags/android14-6.1-" | grep -v "\^{}" | sort -V | tail -1 | cut -d'/' -f3)
        
        if [[ -n "$LATEST_TAG" ]]; then
          echo "Using latest stable tag: $LATEST_TAG"
          repo init -u https://android.googlesource.com/kernel/manifest -b $LATEST_TAG --depth=2
        else
          echo "No stable tag found, using common-android14-6.1 branch"
          repo init -u https://android.googlesource.com/kernel/manifest -b common-android14-6.1 --depth=2
        fi
        
        echo "Starting repo sync..."
        repo sync -c --no-tags -j$(nproc)
        echo "Repo sync completed"
        
        # Verify kernel sources
        if [[ -d "common" ]]; then
          echo "✅ Kernel sources ready"
          cd common
          echo "Kernel version: $(make kernelversion 2>/dev/null || echo 'Unknown')"
          cd ..
        else
          echo "❌ Kernel sources not found"
          exit 1
        fi

    - name: Copy SUSFS module and patches
      run: |
        cd workarea/gki-kernel
        
        echo "Copying SUSFS files..."
        cp -p ../susfs4ksu/kernel_patches/fs/* common/fs/
        cp -p ../susfs4ksu/kernel_patches/include/linux/* common/include/linux/
        cp -p ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-android14-6.1.patch common/
        cp -p ../susfs4ksu/kernel_patches/60_scope-minimized_manual_hooks.patch common/

    - name: Apply SUSFS patches
      run: |
        cd workarea/gki-kernel/common
        
        echo "Applying SUSFS patches..."
        patch -p1 -ui 50_add_susfs_in_gki-android14-6.1.patch
        patch -p1 -ui 60_scope-minimized_manual_hooks.patch

    - name: Setup KernelSU-Next with curl
      run: |
        cd workarea/gki-kernel
        
        echo "Setting up KernelSU-Next..."
        curl -LSs "https://raw.githubusercontent.com/pershoot/KernelSU-Next/refs/heads/next-susfs/kernel/setup.sh" | bash -s next-susfs

    - name: Verify KernelSU integration
      run: |
        cd workarea/gki-kernel/common
        
        echo "=== KernelSU Integration Status ==="
        if [ -d "KernelSU" ]; then
          echo "✅ KernelSU directory found"
          cd KernelSU
          echo "Last 3 commits:"
          git log --oneline -3 || echo "No git history"
          
          echo -e "\nVersion information:"
          find . -name "*version*" -type f | head -5
          grep -r "DRIVER_VERSION\|KERNELSU_VERSION" . | head -3 || echo "Version defines not found"
          cd ..
        else
          echo "❌ KernelSU not found!"
          exit 1
        fi

    - name: Remove protected exports
      run: |
        cd workarea/gki-kernel
        
        echo "Removing protected exports for Wi-Fi/Bluetooth compatibility..."
        sed -i '/^[[:space:]]*"protected_exports_list"[[:space:]]*:[[:space:]]*"android\/abi_gki_protected_exports_aarch64",$/d' common/BUILD.bazel
        rm -f common/android/abi_gki_protected_exports_*
        
        # Clean up patch files
        rm -f common/50_add_susfs_in_gki-android14-6.1.patch common/60_scope-minimized_manual_hooks.patch

    - name: Commit changes
      run: |
        cd workarea/gki-kernel/common
        
        git add -A
        git commit -m "Add KernelSU-Next with SUSFS integration - $KERNEL_NAME"

    - name: Build kernel
      run: |
        cd workarea/gki-kernel
        
        echo "Building kernel with fast configuration..."
        tools/bazel run --config=fast --config=stamp --lto=thin //common:kernel_aarch64_dist -- --dist_dir=../android-kernel

    - name: Prepare kernel image for AnyKernel3
      run: |
        cd workarea/android-kernel
        
        echo "Built artifacts:"
        ls -la
        
        # Find and prepare kernel image
        if [[ -f "Image" ]]; then
          echo "Compressing Image to Image.lz4..."
          lz4 -9 -f Image Image.lz4
          KERNEL_IMAGE="Image.lz4"
        elif [[ -f "Image.gz" ]]; then
          echo "Converting Image.gz to Image.lz4..."
          gunzip Image.gz
          lz4 -9 -f Image Image.lz4
          KERNEL_IMAGE="Image.lz4"
        else
          echo "❌ No kernel image found!"
          exit 1
        fi
        
        echo "KERNEL_IMAGE=${KERNEL_IMAGE}" >> $GITHUB_ENV
        echo "✅ Kernel image prepared: $KERNEL_IMAGE"

    - name: Create AnyKernel3 package
      run: |
        cd workarea
        
        echo "Preparing AnyKernel3 package..."
        cd AnyKernel3
        
        # Copy kernel image
        cp ../android-kernel/$KERNEL_IMAGE .
        
        # Update AnyKernel3 script if needed
        echo "Kernel image: $KERNEL_IMAGE"
        echo "Package contents:"
        ls -la
        
        # Create ZIP package
        ZIP_NAME="${KERNEL_NAME}.zip"
        zip -r9 "../$ZIP_NAME" . -x "*.git*" "README.md" "LICENSE"
        
        cd ..
        echo "✅ Created: $ZIP_NAME"
        echo "Package size: $(du -h $ZIP_NAME | cut -f1)"

    - name: Upload AnyKernel3 package
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.KERNEL_NAME }}
        path: workarea/${{ env.KERNEL_NAME }}.zip
        retention-days: 30

    - name: Upload raw kernel artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.KERNEL_NAME }}-raw-files
        path: workarea/android-kernel/
        retention-days: 15

    - name: Generate build summary
      run: |
        cd workarea
        
        echo "## 🚀 KernelSU Build Complete" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 📦 Package Information" >> $GITHUB_STEP_SUMMARY
        echo "- **Name**: \`$KERNEL_NAME\`" >> $GITHUB_STEP_SUMMARY
        echo "- **Build Date**: $BUILD_DATE" >> $GITHUB_STEP_SUMMARY
        echo "- **Build Time**: $BUILD_TIME UTC" >> $GITHUB_STEP_SUMMARY
        echo "- **Package**: \`$KERNEL_NAME.zip\`" >> $GITHUB_STEP_SUMMARY
        echo "- **Size**: $(du -h $KERNEL_NAME.zip | cut -f1)" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 🔧 Build Components" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ **KernelSU-Next**: Latest with SUSFS integration" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ **SUSFS**: Root hiding capabilities" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ **AnyKernel3**: Universal flashing support" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ **Kernel Image**: \`$KERNEL_IMAGE\`" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### 📋 Raw Artifacts" >> $GITHUB_STEP_SUMMARY
        cd android-kernel
        for file in *; do
          if [[ -f "$file" ]]; then
            echo "- \`$file\` ($(stat -c%s "$file" | numfmt --to=iec-i))" >> $GITHUB_STEP_SUMMARY
          fi
        done
