name: Build GKI Kernel with KernelSU

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Install Dependencies & Setup Tools
      run: |
        # Add Bazel's apt repository
        sudo apt-get update
        sudo apt-get install -y apt-transport-https curl gnupg
        curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor > bazel.gpg
        sudo mv bazel.gpg /etc/apt/trusted.gpg.d/
        echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
        
        # Install all dependencies
        sudo apt-get update
        sudo apt-get install -y git curl rsync bazel
        
        # Setup 'repo' tool
        mkdir -p ~/.bin
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/.bin/repo
        chmod a+x ~/.bin/repo
        echo "$HOME/.bin" >> $GITHUB_PATH

    - name: 2. Download Manifest File
      run: |
        # Please replace 'your_manifest_file.xml' with the actual filename from the enskye/kernel_patches repo.
        curl -o manifest.xml https://raw.githubusercontent.com/enskye/kernel_patches/main/your_manifest_file.xml

    - name: 3. Clone SuSFS Repository
      run: |
        git clone https://gitlab.com/pershoot/susfs4ksu.git -b gki-android14-6.1-dev

    - name: 4. Create Directories
      run: |
        mkdir gki-kernel android-kernel

    - name: 5. Pull Down GKI Repository
      working-directory: ./gki-kernel
      run: |
        repo init -u https://android.googlesource.com/kernel/manifest
        cp ../manifest.xml .repo/manifests/
        repo init -m manifest.xml
        repo sync -j$(nproc --all)

    - name: 6. Create Mirror of GKI Kernel
      run: |
        rsync -a --del gki-kernel/ gki-14

    - name: 7. Copy SuSFS Patches
      working-directory: ./gki-14
      run: |
        cp -p ../susfs4ksu/kernel_patches/fs/* common/fs
        cp -p ../susfs4ksu/kernel_patches/include/linux/* common/include/linux
        cp -p ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-android14-6.1.patch common
        cp -p ../susfs4ksu/kernel_patches/60_scope-minimized_manual_hooks.patch common

    - name: 8. Apply Patches
      working-directory: ./gki-14/common
      run: |
        patch -p1 < 50_add_susfs_in_gki-android14-6.1.patch
        patch -p1 < 60_scope-minimized_manual_hooks.patch

    - name: 9. Integrate KernelSU-Next
      working-directory: ./gki-14
      run: |
        curl -LSs "https://raw.githubusercontent.com/pershoot/KernelSU-Next/refs/heads/next-susfs/kernel/setup.sh" | bash -s next-susfs

    - name: 10. Clean Up Patches and Exports
      working-directory: ./gki-14
      run: |
        sed -i '/^[[:space:]]"protected_exports_list"[[:space:]]:[[:space:]]"android\/abi_gki_protected_exports_aarch64",$/d' common/BUILD.bazel
        rm common/android/abi_gki_protected_exports_aarch64 common/50_add_susfs_in_gki-android14-6.1.patch common/60_scope-minimized_manual_hooks.patch

    - name: 11. Commit Changes
      working-directory: ./gki-14/common
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add -A
        git commit -a -m "Add KernelSU-Next-susfs"

    - name: 12. Build the Kernel
      run: |
        cd gki-14
        tools/bazel run --config=fast --config=stamp --lto=thin //common:kernel_aarch64_dist -- --dist_dir=../android-kernel

    - name: 13. Upload Kernel Artifact
      uses: actions/upload-artifact@v3
      with:
        name: kernel-image
        path: android-kernel/
